In [2]:
import numpy as np
from scipy.stats import binom

In [3]:
# Z-Score calculation for single data point
def zscore(dp, mean, sd):
    """zscore returns the Z-Score of a single data point.

    Args:
        dp (float): Data Point.
        mean (float): Mean.
        sd (float): Standard Deviation.

    Returns:
        float: Z-Score of dp.
    """
    z = (dp - mean) / sd
    return z

zscore(71, 76, 3)

-1.6666666666666667

In [13]:
# Proportion above a value
dp, mu, sd = 0, 25, 50
p = stats.norm.cdf(zscore(dp, mu, sd))
round(p, 4)

0.3085

In [7]:
1/2**3

0.125

In [8]:
0.125 * -100 + 0.875 * 20

5.0

In [9]:
k, n, p = 2, 3, 0.5

binom.pmf(k, n, p) 

0.3750000000000001

In [10]:
k, n, p = 3, 3, 0.5

binom.pmf(k, n, p)

0.125

In [20]:
k, n, p = 0, 4, 0.5

binom.pmf(k, n, p) * 0

0.0

In [21]:
k, n, p = 1, 4, 0.5

binom.pmf(k, n, p) * 3

0.75

In [22]:
k, n, p = 2, 4, 0.5

binom.pmf(k, n, p) * 5

1.875

In [23]:
k, n, p = 3, 4, 0.5

binom.pmf(k, n, p) * 7

1.7500000000000004

In [24]:
k, n, p = 4, 4, 0.5

binom.pmf(k, n, p) * 10

0.625

In [25]:
0.75 + 1.875 + 1.75 + 0.625

5.0

In [31]:
import pandas as pd

In [111]:
ks = np.arange(4)
points = np.array([3000, 1800, 1300, 800])
df = pd.DataFrame({'Correct answers': ks, 'Points': points})
df

Correct answers  Points
0                0    3000
1                1    1800
2                2    1300
3                3     800

In [112]:
n, p = 3, 0.5
df['Probability'] = df['Correct answers'].apply(lambda k: binom.pmf(k, n, p))
df

Correct answers  Points  Probability
0                0    3000        0.125
1                1    1800        0.375
2                2    1300        0.375
3                3     800        0.125

In [113]:
sum(df['Probability'] * df['Points'])

1637.5000000000005

In [114]:
0.017 * 600 + 0.020 * 400

18.200000000000003

In [115]:
0.022 * 750 + 0.027 * 500

30.0

In [119]:
0.4**5 * 10 + (1 - 0.4**5) * -1

-0.8873599999999999

In [120]:
0.3**3 * 15 + (1 - 0.3**3) * -5

-4.46

In [121]:
a = np.array([400, 200, 300])
b = np.array([0.2, 0.2, 0.1])

In [123]:
import pandas as pd

In [132]:
72*50 + 28*10

3880

In [133]:
70*65 + 30*35

5600

In [134]:
0.95**10 * 25 + (1-0.95**10) * -5

12.96210817715136

In [167]:
(20*167 + 5*33) / 200

17.525

In [170]:
p = comb(20, 3) / comb(40, 3)
p

0.11538461538461539

In [171]:
p*300 + (1-p) *-30

8.076923076923084

In [175]:
p = 1/2 * 19/39

In [176]:
p*150 + (1-p)* -20

21.410256410256412

In [178]:
p=0.5**3
p

0.125

In [180]:
5000*0.05 + 3000*0.2 + 8000*0.25

2850.0

In [190]:
p, k = 0.3, 3
k**p * 50 + (1-k**p) * -2

70.30023685642728

In [188]:
p, k = 0.8, 4
k**p * 70 + (1-k**p) * -2

216.26318557749735

In [206]:
0.3**3

0.026999999999999996

In [207]:
0.3**3*50 + (1-0.3**3)*-2

-0.5960000000000001

In [202]:
0.8**4*70 + (1-0.8**4)*-2

27.491200000000003

In [204]:
0.3**3

0.026999999999999996

In [208]:
2000 * 0.1 + 4000 * 0.15

800.0

In [211]:
df = pd.DataFrame({
    "Type of virus": ["Pikachu", "Trojan", "ADA"], 
    "Cost of repair $": [200, 100, 400],
    "Probability": [0.25, 0.15, 0.1]})

df

Type of virus  Cost of repair $  Probability
0       Pikachu               200         0.25
1        Trojan               100         0.15
2           ADA               400         0.10

In [213]:
400 * 0.1 + 100

140.0

In [212]:
np.sum(df["Cost of repair $"] * df.Probability)

105.0

In [214]:
48 + 73

121

In [215]:
146*5

730

In [216]:
121*5

605

In [218]:
k, n, p = 2, 4, 0.5
p = binom.cdf(k, n, p)

In [219]:
p*1 + (1-p)*-3

-0.25

In [220]:
k, n, p = 5, 5, 0.5
p = binom.pmf(k, n, p)

In [222]:
p*100 + (1-p)*-4

-0.75

In [1]:
from utils.norm import norm_prop

In [2]:
# Proportion above a value
dp, mu, sd = 30, 26, 2
p = norm_prop(dp, mu, sd, 'below')
p

TypeError: 'module' object is not callable

In [3]:
from scipy.stats import norm

In [5]:
norm.cdf(30, 26, 2)

0.9772498680518208

In [5]:
from utils.src.stats import zscore
type(zscore)

function

In [8]:
zscore(1, 0, 1)

1.0

In [2]:
from utils.src.stats import norm_prop
type(norm_prop)

function

In [15]:
import utils.src.norm.norm_prop as norm_prop
type(norm_prop)

module

In [44]:
import numpy as np
from utils.src.stats import zscore, norm_prop, norm_rv
from scipy.stats import binom, norm, geom
from scipy.special import comb

In [6]:
# Proportion above a value
dp, mu, sd = 1, 1, 0.05
precision = 2
p = norm_prop(dp, mu, sd, 'below')
p = round(p, precision)
p

0.5

In [25]:
k, n, p = 3, 5, 0.6
binom.pmf(k, n, p)

0.3455999999999997

In [28]:
comb(5, 3) * 0.6**3 * 0.4**2

0.3456

In [19]:
n, p = 15, 0.3
binom.mean(n, p)

4.5

In [20]:
binom.std(n, p)

1.7748239349298849

In [23]:
arr = np.array([58, 213, 522])

In [24]:
arr / arr.sum()

array([0.07313997, 0.26860025, 0.65825977])

In [29]:
4*33 + 2*8

148

In [52]:
0.16+0.128+0.512

0.8

In [63]:
k, n, p = 1, 3, 0.9
binom.pmf(k, n, p)

0.027

In [65]:
n, p = 3, 0.06
precision = 2
cdf = geom.cdf(n, p)
cdf = round(cdf, precision)
cdf

0.17

In [62]:
n, p = 6, 0.06
precision = 2
pmf = geom.pmf(n, p)
pmf = round(pmf, precision)
pmf

0.04

In [72]:
dp = 736
mus = [175]*4
sds = [15]*4
method = 'T'
area = 'above'
p = round(1 - norm_rv(dp, mus, sds, method, area), 2)

p

0.88

In [73]:
norm_rv?

Signature: norm_rv(dp, mus, sds, method, area)
Docstring:
norm_rv calculates the combination of random variables then calling function norm_prop to return the proportion of a specific area based on dp.

Args:
    dp (float or array like): Data Point. float for area = 'below' or area = 'high'; array like (2 float) for area = 'between'.
    mus (array like): Collection of means.
    sds (array like): Collention of standard deviations.
    method (str): One of 'T'(Total) or 'D'(Difference).
    area (str, optional): The specific area ('below', 'above', or 'between') of the normal distribution based on dp. Defaults to 'below'.

Raises:
    ValueError: method must be one of 'T' or 'D'

Returns:
    float: The proportion of a specific area based on dp.
File:      ~/Git/Data Science Projects/statistics and probability/utils/src/_stats/norm/norm_rv.py
Type:      function


In [69]:
dp, mu, sd = 736, 175*4, 15*4
1 - norm.cdf(dp, mu, sd)

0.27425311775007355

In [71]:
norm_prop(dp, mu, sd, "above")

0.27425311775007355

In [79]:
dp = 736
mus = [175]*4
sds = [15]*4
method = 'T'
area = 'above'
p = round(norm_rv(dp, mus, sds, method, area), 2)

p

0.12

In [76]:
dp = 290
mus = [65]*4
sds = [12]*4
method = 'T'
area = 'above'
p = round(norm_rv(dp, mus, sds, method, area), 2)

p

0.11

In [80]:
30000 * 19 + 40000 * 2 + 50000 * 6 + 60000 * 17 + 70000 * 6

2390000

In [81]:
2390000 / 50

47800.0

In [83]:
47800.0 * 70

3346000.0

In [84]:
50*0.99

49.5

In [85]:
3/21

0.14285714285714285

In [87]:
0.12 + 3*0.42+7*0.52

5.02

In [88]:
0.98 * -600 + 0.02 * (50000-600)

400.0

In [90]:
0.09 + 0.03*2 +0.52*3 + 0.24*4 + 0.12 *5

3.27

In [92]:
-10 * 0.995 + (500 - 10) * 0.005

-7.499999999999999

In [97]:
def rv_mean(X, P):
    """rv_mean calculates the expected value (also known as mean) of the random variable X.

    Args:
        X (array like): Random Variable X.
        P (array like): The probability distribution of random variable X.

    Returns:
        float: The expected value (also known as mean) the random variable X.
    """
    mu = np.average(a=X, weights=P)

    return mu

In [98]:
def rv_std(X, P):
    """rv_std calculates the standard deviation of the random variable X.

    Args:
        X (array like): Random Variable X.
        P (array like): The probability distribution of random variable X.

    Returns:
        float: The standard deviation of the random variable X.
    """
    mu = rv_mean(X, P)
    sd = np.sum((X - mu)**2 * P)**0.5

    return sd

In [105]:
X = np.array([60, -9940])
P = np.array([.999, .001])

In [106]:
rv_std(X, P)

316.06961258558215

In [108]:
k = np.array([3, 4])
n = np.array([10, 10])
comb(n, k, exact=False)

array([120., 210.])

In [118]:
#k = np.array([3, 4])
#n = np.array([10, 10])
k = np.array([1, 1])
n = np.array([10, 10])
comb(n, k, exact=False)

array([10., 10.])

In [120]:
n = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
k = 1
comb(n, k)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [173]:
comb(5, 2)

10.0

In [128]:
import itertools
from itertools import product

In [174]:
red = np.arange(1, 7)
green = np.arange(1, 7)

In [175]:
combs = np.array(list(product(red, green)))
combs

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [1, 6],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 5],
       [2, 6],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 5],
       [3, 6],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 5],
       [4, 6],
       [5, 1],
       [5, 2],
       [5, 3],
       [5, 4],
       [5, 5],
       [5, 6],
       [6, 1],
       [6, 2],
       [6, 3],
       [6, 4],
       [6, 5],
       [6, 6]])

In [176]:
len(combs)

36

In [177]:
p_more_than_12 = np.sum(np.sum(combs, axis=1) > 7) / len(combs)
p_equal_to_12 = np.sum(np.sum(combs, axis=1) == 7) / len(combs)
p_less_than_12 = np.sum(np.sum(combs, axis=1) < 7) / len(combs)
print(p_more_than_12)
print(p_equal_to_12)
print(p_less_than_12)

0.4166666666666667
0.16666666666666666
0.4166666666666667


In [181]:
E = p_more_than_12 * 5 + p_equal_to_12 * 0 + p_less_than_12 * -4
E = round(E, 2)
E

0.42